[tool.poetry]
name = "norm"
version = "1.3.2"
description = "Easy peasy SQL generation"
authors = ["Justin Van Winkle <justin.vanwinkle@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2.2"
pytest-flake8 = "^1.0.4"
psycopg2 = "^2.8.4"
pymssql = "^2.1.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
